### ISSUE TITLE
Claiming 404 on a project homepage, but it loads without issue

### ISSUE THREAD

**Issue by anadon** [repology/repology-linkchecker#25]
Looking at https://repology.org/repository/gnuguix/problems as of May 31, 2020 at `ascii2binary`.  The warning says that the page gives a 404, but it loads just fine when I navigate to it.  What might be going on here?

**Comment by AMDmi3** [comment]
This is in fact not related to the link checker. Here's its status, accessible via the link in the problem:

https://repology.org/link/https://billposer.org/Software/a2b.html

The actual issue is that that problems are not updated when link status changes, it's known repology/repology-updater#1053. For this case, forcing the update to remove outdated problems.
